### ISSUE TITLE
Runtime error on Windows machine

### ISSUE THREAD

**Issue by nnahito** [keitakurita/twitter_past_crawler#24]
はじめまして。
Windowsマシンで、twitterpastcrawlerのサンプルを実行させていただくと、

```
FileNotFoundError: [Errno 2] No such file or directory: '   （略）  useragent_windows.dat'
```

が表示されました。
これは、twitterpastcrawler.pyの14行目が
```python
uafile = "useragent_windows.dat"
```
となっているのが原因ではないかと思います。
よろしければご対応をお願い致します。

**Comment by keitakurita** [comment]
ご指摘ありがとうございます．
指摘していただいた箇所を修正しました．windows環境が今ない関係上，まだ動作確認は行なっていませんが，これで動くかどうかを試していただけないでしょうか？
よろしくお願いいたします．

**Comment by nnahito** [comment]
正常動作を確認できました！
ありがとうございます！！
